### PR TITLE
extract version number for PureScript

### PR DESCRIPTION
**Pull request by seanstrom**
Thought it would be nice to only need to update the version of PureScript in one place.
Seems like this was once the case before the changes for PureScript 0.7.0 were merged.
Any reason to not have the PureScript version in one place?

### CODE REVIEW

**Comment by seanstrom** [comment]
@garyb @shinnn thoughts?

**Comment by garyb** [comment]
Sounds good to me in principle, I've not looked at it yet as I'm on holiday at the moment. :wink:

**Comment by seanstrom** [comment]
Oops, sorry to bother :stuck_out_tongue_closed_eyes: 
Take your time and enjoy :smile:

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
