### PR TITLE
Update to PSC 0.10.2.

### PR DESCRIPTION
**Pull request by chexxor**

### CODE REVIEW

**Comment by shinnn** [comment]
@paf31 I downloaded the tar.gz archive from [the v0.10.2 release page](https://github.com/purescript/purescript/releases/tag/v0.10.2) but I found it doesn't contains the new tool `psc-package`. Did you exclude it on purpose?

**Comment by chexxor** [comment]
Perhaps "psc-package" needs to be added here? https://github.com/purescript/purescript/blob/master/bundle/build.sh#L29

**Comment by garyb** [comment]
`psc-publish` is now included - I reuploaded the 0.10.2 archives to accommodate this, and in the future it'll be present by default.

**Comment by shinnn** [comment]
Published v0.10.2 to npm. Thanks again, @chexxor!

**Comment by garyb** [comment]
Thanks to both of you!

**Pull request merged**
