### PR TITLE
Make it compatible with both Node v4 (current LTS) and the latest ver.

### PR DESCRIPTION
**Pull request by kRITZCREEK**

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
It doesn't seem right that I have to remove all kinds of ES6 things for compatibilty with the newest node version :D

**Comment by kRITZCREEK** [comment]
Allright that's it from me. If there is a better way to do this feel free to close this PR.

**Comment by shinnn** [comment]
Really nice! Thanks, @kRITZCREEK.

**Comment by kRITZCREEK** [comment]
:+1:

**Comment by michaelmior** [comment]
Would be great to have a new release with this for Node v6 installs if possible :) Thanks for fixing so quickly!

**Comment by garyb** [comment]
I'm not sure how best to achieve that right now. We like to keep the version in sync with the compiler release because it can result in quite a bit of confusion for users when the versions don't match up. 

Since this is `npm` we can't reuse the same version that is currently published, and if we called it `v0.8.5-node6` that would be considered < `v0.8.5` by semver, so that doesn't seem right either. That might be the way to go though, and then people who need it can add the dependency as an exact version rather than `^` bounded. This is the last 0.8.x release anyway, so maybe that's acceptable.

Ideas anyone?

**Comment by kRITZCREEK** [comment]
Maybe through the `npm install purescript@next` mechanism?

**Comment by garyb** [comment]
Yeah, I figured we'd make a dist tag for it, but it'll need versioning as well as that.

**Comment by hdgarrood** [comment]
I think the most sensible approach would be to release an 0.8.6 which is the same as 0.8.5 just for this, if it's urgent enough. Otherwise, just wait for the next 'real' compiler release.

**Comment by shinnn** [comment]
Just released v0.8.6-rc.1.

**Comment by damncabbage** [comment]
@shinnn: As said above:
> and if we called it v0.8.5-node6 that would be considered < v0.8.5 by semver

... This doesn't get installed by default.
```
$ nvm use 6
Now using node v6.0.0 (npm v3.8.6)
$ npm install --save-dev purescript

> purescript@0.8.5 postinstall /Users/rhoward/code/experiments/tmppsc/node_modules/purescript
> node --harmony_destructuring lib/install.js

node: bad option: --harmony_destructuring
...
```

@hdgarrood: Given this is now broken out of the box for new users, I'd consider this urgent unless the next version is going to drop, like, this week.

**Comment by hdgarrood** [comment]
Fair enough.

@shinn sorry, I meant a real compiler release. Please don't make releases of node-purescript-bin unless there is a real purescript release to go with them. If we do release an 0.8.6 it's going to be really confusing.

I think the reason 0.8.6-RC.1 doesn't get picked up by an `npm install purescript` is not to do with semver but rather dist tags. If we want that command to give you 0.8.6-rc.1, then someone who has access to the npm package just needs to set the `latest` tag.

**Comment by hdgarrood** [comment]
Oops, looking back I guess I wasn't very clear about what I meant, was I, sorry. I meant do a 'fake' compiler release that's the same as 0.8.5 and call it 0.8.6 (as opposed to a 'real' release which has new features etc).

**Comment by shinnn** [comment]
https://github.com/purescript-contrib/node-purescript-bin/pull/20#issuecomment-216032586

> I'd consider this urgent unless the next version is going to drop, like, this week.

@damncabbage No. this project is licensed under the MIT license. Read it carefully.

> IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

https://github.com/purescript-contrib/node-purescript-bin/pull/20#issuecomment-216033979

> Please don't make releases of node-purescript-bin unless there is a real purescript release to go with them. If we do release an 0.8.6 it's going to be really confusing.

@hdgarrood I think existing at least one version, which doesn't strictly follow the upstream PureScript version though, is much better than there is no option for Node v6 users.

**Comment by shinnn** [comment]
https://twitter.com/damncabbage/status/726775190428913665

> I'm not sure why you locked the thread; I apologise if I came across as at all rude by saying that it was somewhat urgent.

@garyb @hdgarrood Feel free to unlock this issue and continue discussion if you want.

**Pull request merged**
